// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAA: typeof import("./src/components/AAA.vue")["default"]
    AAAA: typeof import("./src/components/AAAA.vue")["default"]
    Collapse: typeof import('./src/components/Collapse.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import("element-plus/es")["ElBadge"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImag: typeof import('element-plus/es')['ElImag']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"]
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import("element-plus/es")["ElTabPane"]
    ElTabs: typeof import("element-plus/es")["ElTabs"]
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PreviewItemsCard: typeof import('./src/components/PreviewItemsCard.vue')['default']
    ProductInformation: typeof import('./src/components/ProductInformation.vue')['default']
    ProductLocation: typeof import('./src/components/ProductLocation.vue')['default']
    ProductPage: typeof import("./src/components/ProductPage.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabAboutProduct: typeof import('./src/components/TabAboutProduct.vue')['default']
  }
}
